controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    diff cont:
      type: diff_drive_controller/DiffDriveController

    joint broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:
    
    publish_rate: 50.0

    base_frame_id: base_link

    left_wheel_names: ['left_front_wheel_joint', 'left_back_wheel_joint']
    right_wheel_names: ['right_front_wheel_joint', 'right_back_wheel_joint']
    wheel_separation: 0.1905
    wheel_radius: 0.025
    wheels_per_side: 2
    
    use_stamped_vel: false